# roles/pve_storage/defaults/main.yml
---
# Disk partition pattern
disk_pattern: "/dev/sd*1"

# Filesystem type for individual disks
disk_fstype: ext4

# Mount options for individual disks
disk_mount_opts: defaults,nofail,noatime

# Base path for individual disk mounts
disk_mount_base: /mnt/disks

# MergerFS pool path
mergerfs_pool_path: /mnt/pool

# MergerFS options
mergerfs_opts: "defaults,nonempty,allow_other,use_ino,category.create=epmfs,moveonenospc=true,minfreespace=96G,fsname=mergerfs"
